# This is a basic workflow to help you get started with Actions

name: DevOpsHomework

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Env
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_NAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build and push to dockerhub
        run: |
          ls -a
          docker build -t shishochik/devopshomework:0.1
          docker push shishochik/devopshomework:0.1
  send-result-to-tg:
    runs-on: ubuntu-latest
    environment: Env
    needs: docker
    steps:
      - name: send result
        uses: appleboy/telegram-action@master
        with:
            to: ${{secrets.TG_MY_ID}}
            token: ${{secrets.TG_TOKEN}}
            message: |
              ${{github.actor}} create a commit ${{github.event.commits[0].message}} in ${{github.repository}}, ${{needs.docker.result}}
