# This is a basic workflow to help you get started with Actions

name: DevOpsHomework

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    environment: Env
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_NAME}}
          password: ${{secrets.DOCKER_TOKEN}}
      - name: Build and push to dockerhub
        run: |
          ls -a
          docker build -t shishochik/devopshomework:0.1 .
          docker push shishochik/devopshomework:0.1
  send-about-fail:
    runs-on: ubuntu-latest
    environment: Env
    needs: docker
    if: ${{failure()}}
    steps:
      - name: send to tg about fail
        uses: appleboy/telegram-action@master
        with:
            to: ${{secrets.TG_MY_ID}}
            token: ${{secrets.TG_TOKEN}}
            message: |
              ${{github.actor}} create a commit ${{github.event.commits[0].message}} in ${{github.repository}}, fail
  send-about-success:
    runs-on: ubuntu-latest
    environment: Env
    needs: docker
    if: ${{success()}}
    steps:
      - name: send to tg about success
        uses: appleboy/telegram-action@master
        with:
            to: ${{secrets.TG_MY_ID}}
            token: ${{secrets.TG_TOKEN}}
            message: |
              ${{github.actor}} create a commit ${{github.event.commits[0].message}} in ${{github.repository}}, success
